import { Security } from './security';
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';

// auto-generated by angular 
// describe('Security', () => {
//   it('should create an instance', () => {
//     expect(new Security()).toBeTruthy();
//   });
// });



